default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: proxyfield_development

test:
  <<: *default
  database: proxyfield_test<%= ENV['TEST_ENV_NUMBER'] %>


production:
  primary:
    <<: *default
    database: proxyfield_production
    # Fly.io PostgreSQL configuration
    url: <%= ENV['DATABASE_URL'] %>
    host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } unless ENV['DATABASE_URL'] %>
    username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } unless ENV['DATABASE_URL'] %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } unless ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    database: proxyfield_production_cache
    # Fly.io PostgreSQL configuration for cache
    url: <%= ENV['CACHE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } unless ENV['DATABASE_URL'] %>
    username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } unless ENV['DATABASE_URL'] %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } unless ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: proxyfield_production_queue
    # Fly.io PostgreSQL configuration for queue
    url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } unless ENV['DATABASE_URL'] %>
    username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } unless ENV['DATABASE_URL'] %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } unless ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: proxyfield_production_cable
    # Fly.io PostgreSQL configuration for cable
    url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } unless ENV['DATABASE_URL'] %>
    username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } unless ENV['DATABASE_URL'] %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } unless ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
