# Sidekiq configuration file
development:
  :concurrency: 5
  :max_retries: 3
  :timeout: 60

production:
  :concurrency: 10
  :max_retries: 5
  :timeout: 60

test:
  :concurrency: 1
  :max_retries: 1
  :timeout: 60

# Specify Redis connection
:redis:
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>

# Configure queues with priorities
:queues:
  - [critical, 6]
  - [default, 4]
  - [mailers, 3]
  - [low, 2]

# Enable strict queue ordering (process queues in order listed)
:strict: false

# Log level
:verbose: <%= ENV['RAILS_ENV'] == 'development' %>

# Sidekiq will run this file through ERB when reading it, so you can embed Ruby code
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log

# Dead job retention (in seconds, default is 6 months)
:dead_max_jobs: 10000
:dead_timeout_in_seconds: 15552000 # 6 months
