name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI"]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    # Only deploy if CI passed (when triggered by workflow_run) or on direct push to main
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --dockerfile Dockerfile.production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deployment notification
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deployment successful!"
            echo "🚀 App is live at: https://proxyfield-app.fly.dev"
          else
            echo "❌ Deployment failed!"
            exit 1
          fi