name: RuboCop

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.5'
        bundler-cache: true

    - name: Run RuboCop
      run: bundle exec rubocop
